const ShopActionTypes = {
    FETCH_COLLECTION_START : 'FETCH_COLLECTION_START',
    FETCH_COLLECTION_SUCCESS : 'FETCH_COLLECTION_SUCCESS',
    FETCH_COLLECTION_FAILURE : 'FETCH_COLLECTION_FAILURE',
    UPDATE_COLLECTIONS: 'UPDATE_COLLECTIONS'
}

export default ShopActionTypes;