export const CART_ACTION_TYPE = {
    TOGGLE_CART_DROPDOWN: 'TOGGLE_CART_DROPDOWN',
    ADD_ITEM : 'ADD_ITEM',
    CLEAR_ITEM_FROM_CART: 'CLEAR_ITEM_FROM_CART',
    REMOVE_ITEM_FROM_CART: 'REMOVE_ITEM_FROM_CART'
}